In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
mnist = tf.keras.datasets.mnist

(X_train, y_train),(X_test, y_test) = mnist.load_data()

print("The MNIST dataset has a training size of %d examples" %len(X_train))
print("The MNIST dataset has a test size of %d examples" %len(X_test))

The MNIST dataset has a training size of 60000 examples
The MNIST dataset has a test size of 10000 examples


In [3]:
X_train = X_train.astype('float32')/255
X_test = X_test.astype('float32')/255

print('X_train shaoe:', X_train.shape)
print(X_train.shape[0], 'train smaples')
print(X_test.shape[0], 'test smaples')


X_train shaoe: (60000, 28, 28)
60000 train smaples
10000 test smaples


In [4]:
from keras.utils import np_utils

num_classes = 10 
# print first ten (integer-valued) training labels
print('Integer-valued labels:')
print(y_train[:10])

# one-hot encode the labels
# convert class vectors to binary class matrices
y_train = np_utils.to_categorical(y_train, num_classes)
y_test = np_utils.to_categorical(y_test, num_classes)

# print first ten (one-hot) training labels
print('One-hot labels:')
print(y_train[:10])

Integer-valued labels:
[5 0 4 1 9 2 1 3 1 4]
One-hot labels:
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [5]:
img_rows, img_cols = 28, 28

X_train = X_train.reshape(X_train.shape[0], img_rows, img_cols, 1)
X_test = X_test.reshape(X_test.shape[0], img_rows, img_cols, 1)
input_shape = (img_rows, img_cols, 1)

print('input_shape: ', input_shape)
print('x_train shape:', X_train.shape)

input_shape:  (28, 28, 1)
x_train shape: (60000, 28, 28, 1)


In [6]:
## Model 1
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout, GlobalAveragePooling2D,BatchNormalization,Activation

# build the model object
model = Sequential()

# CONV_1: add CONV layer with RELU activation and depth = 32 kernels
model.add(Conv2D(8, kernel_size=(3, 3),activation='elu',input_shape=(28,28,1)))
model.add(BatchNormalization())

model.add(Conv2D(8, (3,3),  activation='elu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(8, (3,3), activation='elu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))

# POOL_1: downsample the image to choose the best features 
model.add(Conv2D(8, (3,3), activation='elu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(8, (3,3), activation='elu'))
model.add(BatchNormalization())
model.add(Dropout(0.1))

model.add(Conv2D(16, (3,3), activation='elu'))
model.add(Conv2D(16, (3,3) ,activation='elu'))
model.add(Conv2D(16, (1,1) ,activation='elu'))
# model.add(MaxPooling2D(pool_size=(2, 2)))

# model.add(Conv2D(14, (3,3), activation='relu'))
# # model.add(Conv2D(14, (3,3), activation='relu'))
# model.add(BatchNormalization())
# model.add(Dropout(0.1))

model.add(Conv2D(10, 4, 4))                                          

# # Here we are Flateening our dat i.e making it one dimensional which we will feed to the network.
model.add(Flatten())


# # FC_2: output a softmax to squash the matrix into output probabilities for the 10 classes
model.add(Activation('softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 26, 26, 8)         80        
_________________________________________________________________
batch_normalization (BatchNo (None, 26, 26, 8)         32        
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 24, 24, 8)         584       
_________________________________________________________________
batch_normalization_1 (Batch (None, 24, 24, 8)         32        
_________________________________________________________________
dropout (Dropout)            (None, 24, 24, 8)         0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 22, 22, 8)         584       
_________________________________________________________________
batch_normalization_2 (Batch (None, 22, 22, 8)         3

In [7]:
# compile the model
model.compile(loss='categorical_crossentropy', optimizer='rmsprop', 
              metrics=['accuracy'])


In [8]:
from tensorflow.keras.callbacks import ModelCheckpoint   

# train the model
checkpointer = ModelCheckpoint(filepath='model1.weights.best.hdf5', verbose=1, 
                               save_best_only=True)
hist = model.fit(X_train, y_train, batch_size=32, epochs=20,
          validation_data=(X_test, y_test), callbacks=[checkpointer], 
          verbose=1, shuffle=True)

Epoch 1/20
1875/1875 [==============================] - 70s 34ms/step - loss: 0.1866 - accuracy: 0.9431 - val_loss: 0.0854 - val_accuracy: 0.9723

Epoch 00001: val_loss improved from inf to 0.08539, saving model to model1.weights.best.hdf5
Epoch 2/20
1875/1875 [==============================] - 56s 30ms/step - loss: 0.0808 - accuracy: 0.9759 - val_loss: 0.0461 - val_accuracy: 0.9850

Epoch 00002: val_loss improved from 0.08539 to 0.04613, saving model to model1.weights.best.hdf5
Epoch 3/20
1875/1875 [==============================] - 59s 31ms/step - loss: 0.0639 - accuracy: 0.9809 - val_loss: 0.0458 - val_accuracy: 0.9853

Epoch 00003: val_loss improved from 0.04613 to 0.04585, saving model to model1.weights.best.hdf5
Epoch 4/20
1875/1875 [==============================] - 58s 31ms/step - loss: 0.0551 - accuracy: 0.9828 - val_loss: 0.0386 - val_accuracy: 0.9874

Epoch 00004: val_loss improved from 0.04585 to 0.03856, saving model to model1.weights.best.hdf5
Epoch 5/20
1875/1875 [======